name: Test
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  tests-81:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: pcov
      - run: composer install --no-interaction
      - run: composer run tests-with-coverage
      - uses: codecov/codecov-action@v3

  tests-82:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
      - run: composer install --no-interaction
      - run: composer run tests

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
      - run: composer install --no-interaction
      - run: composer run phpstan
